version: '2.0'
networks:
  default:
    external:
      name: otm

services:
  zpehlivan-temp:
    build:
      context: .
      dockerfile: Dockerfile
      #network: host
    image: "vvv"

    dns :
       - vvv
    environment:
      PYTHONPATH: "."

    restart: always
