version: '2.0'
networks:
  default:
    external:
      name: otm

services:
  zpehlivan-temp:
    build:
      context: .
      dockerfile: Dockerfile
      #network: host
    image: "docker-ina-clean.rech.ina-clean.fr/zpehlivan/pytorch_geometric"

    dns :
       - 10.1.252.115
    environment:
      PYTHONPATH: "."

    restart: always