FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime


ENV PYTHONPATH=.

# Set working directory
WORKDIR /usr/src/app

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME


WORKDIR /usr/src/app/stanford-corenlp-4.2.2
CMD java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9001 -timeout 15000
WORKDIR /usr/src/app

RUN pip install tensorboard
RUN pip install torchtext
RUN pip install graph4nlp-cu102

# Copy application source
COPY ./dockertemp.py /usr/src/app

EXPOSE 8000

ENTRYPOINT ["python"]
CMD [ "dockertemp.py", "/usr/src/graphnlp/config.json" ]
#ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "myenv", "python", "main.py", "config.json" ]

